[tesseract]
path = "C://Program Files//Tesseract-OCR"

[image]
directory = "D://My Documents//Video"
keyword = "Screenshot"
crop = [352, 40, 600, 80]

[output]
expert = true
master = true
append = false
fc = true
ap = false
